import catchAsync from '../utils/catchError.js';

export const createBooking = catchAsync(async (req, res, next) => {});

export const getBooking = catchAsync(async (req, res, next) => {});

export const confirmBooking = catchAsync(async (req, res, next) => {});

export const completeBooking = catchAsync(async (req, res, next) => {});

export const getMyBookings = catchAsync(async (req, res, next) => {});

export const cancelBooking = catchAsync(async (req, res, next) => {});

export const getEscortBookings = catchAsync(async (req, res, next) => {});

export const disputeBooking = catchAsync(async (req, res, next) => {});

export const setBookingBuffer = catchAsync(async (req, res, next) => {});
